before_script:
  - docker version
  - docker-compose version
stages:
  - build
  - deploy
build:
  stage: build
  script:
    - docker system prune -f
    - docker image prune --force
  only:
    - develop
deploy:
  stage: deploy
  script:
    - cp .env.example .env
    - docker-compose up -d --build
    - docker-compose exec app composer install --ignore-platform-reqs
    - docker-compose exec app php artisan migrate
    - docker-compose exec app php artisan storage:link
    - sudo chmod -R 777 ./storage && sudo chmod -R 777 ./bootstrap/cache
  only:
    - develop
